### ISSUE TITLE
ReferenceError: logger is not defined

### ISSUE THREAD

**Issue by nikovanmeurs** [and3rson/node-nameko-client#4]
Hi,

I just ran into an error in our backend caused by an undefined reference in nameko.js:
```
ReferenceError: logger is not defined
    at /src/riddles/node_modules/node-nameko-client/nameko.js:151:21
    at Exchange.publish (/src/riddles/node_modules/amqp/lib/exchange.js:238:12)
    at Promise (/src/riddles/node_modules/node-nameko-client/nameko.js:137:28)
    at NamekoClient.call (/src/riddles/node_modules/node-nameko-client/nameko.js:117:23)
```

The issue is caused because the logging call at line 151 needs `self.` prepended in front of it.

**Comment by and3rson** [comment]
Merged, thanks!
